MediaSession.md
This is motivated by @jernoble's explanation of the iOS model, as it
does not seem like media playback is required, only an active media
session. This hasn't been verfied, however:
https://github.com/whatwg/media-keys/issues/9#issuecomment-75272483
=> Simplify MediaSession somewhat to not require audio playback

ImplicitMediaControls.md, README.md
I realized I had not properly documented the proposal to implicitly provide media focus, key binding, events and overrides around `HTMLMediaElement`. This pull request remedies that.
This pull request also replaces the two HTMLMediaElement-based proposals that were documented in the README. Those are replaced with the contents of this commit.
=> Add implicit media controls proposal based around HTMLMediaElement objects

ImplicitMediaControls.md
Fixes previous pull request review comment @ https://github.com/whatwg/media-keys/pull/22#discussion_r27494601.
=> Remove 'focusable media element' references

mediasession.bs, mediasession.html
This is (hopefully) a more memorable name, and is in analogy to the
"slaved media elements" of media controllers.
Just like slaved media elements, the set does not need to be maintained
explicitly, since it's defined by which media elements have a media
session as its current media session, so it's always in sync.
This leaves the concept unused, but it won't be for long.
=> Rename "session media elements" to "participating media elements"

mediasession.bs, mediasession.html
This is the terminology used in many specs:
http://dev.w3.org/csswg/cssom/#extensions-to-the-document-interface
http://dev.w3.org/csswg/cssom-view/#extensions-to-the-htmlimageelement-interface
http://w3c.github.io/selection-api/#extensions-to-document-interface
http://w3c.github.io/webcomponents/spec/shadow/#extensions-to-element-interface
http://w3c.github.io/web-animations/#extensions-to-the-document-interface
Also remove the ID overrides since the default ones are good.
=> Use the "extensions to" terminology in place of "additions to"

mediasession.bs, mediasession.html
kind="" corresponds to a default media session, which doesn't have
an expose MediaSession object on which to observe the empty string.
=> Drop the empty string from MediaSessionKind

mediasession.bs, mediasession.html
This is for consistency with the deactivation algorithm and the fact
that this is under the section "Activating a media session".
=> Rename the invocation algorithm to the activation algorithm

mediasession.bs, mediasession.html
There are a few open issues around remote controls:
https://github.com/whatwg/mediasession/issues/11
https://github.com/whatwg/mediasession/issues/21
https://github.com/whatwg/mediasession/issues/42
https://github.com/whatwg/mediasession/issues/45
https://github.com/whatwg/mediasession/issues/56
In particular issue 45 will change this API a lot, so in order to not
tempt implementors into going with this design, remove it for now.
Much of this, in particular the prose and example, can be revived
once we have the time to hammer out the flattened API design.
=> Remove the MediaRemoteControls interface pending flattening

mediasession.bs, mediasession.html
There are no paths into this algorithm with arbitrary strings.
Fixes https://github.com/whatwg/mediasession/issues/72
=> Remove prose for handling invalid media session kinds internally

mediasession.bs, mediasession.html
It's still not clear if we should attempt to standardize the default
behavior, but if we do it should probably be as one of the existing
media session kinds, but where the media session instance cannot be
accessed by scripts.
=> Drop the concept of a default session as a separate category

mediasession.bs, mediasession.html
This is mostly to get rid of the reference to the top-level browsing
context, and to say that a media session can have zero members.
Related to https://github.com/whatwg/mediasession/issues/100 and
https://github.com/whatwg/mediasession/issues/50
=> Tweak the definition of what a media session represents

mediasession.bs, mediasession.html
There's still an open spec issue for this:
https://github.com/whatwg/mediasession/issues/112
In the implementation we use DOMException, so spec that for now:
https://codereview.chromium.org/1370453002/
=> Reject the activate() promise with an InvalidStateError DOMException

mediasession.bs
In order to make the shared Media Session example clearer, I believe it's better to explicitly create this variable.
PS: Please run bikeshed afterwards as I don't know which version you used.
R=@mounirlamouri
=> Add sharedSession variable to example

mediasession.bs, mediasession.html
Make the artwork spec more like WebApp manifest icons, which has `src`,
`type` and `sizes` fields. The texts are based on pull request #126 
Fixes #56
=> Manifest-icon-like metadata artworks.

index.bs
Please take a look. Though it is still rough now.
=> Updating the spec to match current explainer

explainer.md, index.bs
This pull request addresses recent changes as discussed in #136, i.e. allowing child frame MediaSession to be routed.
=> Allow MediaSession in child frames to be selected

explainer.md, index.bs
Changes:
* Added playback state
* Removed playpause action
* Some structural change in "Processing model" section
The temporary spec after the change can be found at:
http://xxyzzzq.github.io/mediasession/
=> Add playbackState attribute and remove playpause action

index.bs
This is also making more clear in the spec when to run the update
metadata algorithm and requests it to be bundled via tasks queuing
for attribute changes.
Furthermore, the commit is doing some cosmetics/authoring changes.
=> Make MediaMetadata attribute writable (closes #116)

index.bs
=> Add setActionHandler() and rewrite parts of the specification related to controls handling (closes #147, closes #148)

index.bs
'' -> ""
Exposed=(Window) -> Exposed=Window (seems to only be needed for the root interface)
various typos and a missing comma
=> Fix some typos and inconsistencies

index.bs
This PR adds a "skip ad" media session action that may be used by media notification and [picture-in-picture window controls](https://github.com/WICG/picture-in-picture/pull/69#issuecomment-432516966
)
Note that one already exists in Android Media Session: https://developer.android.com/reference/kotlin/android/support/v4/media/session/MediaSessionCompat#ACTION_SKIP_AD
We may want to add support for media session actions feature detection. WDYT?
@mounirlamouri
=> Add new skip-ad media session action

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/beccahughes/mediasession/pull/210.html" title="Last updated on May 2, 2019, 11:08 PM UTC (e52e086)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/mediasession/210/3d0f74b...beccahughes:e52e086.html" title="Last updated on May 2, 2019, 11:08 PM UTC (e52e086)">Diff</a>
=> Add position state to the spec

CONTRIBUTING.md, LICENSE.md, README.md, index.bs, security-privacy-questionnaire.md, w3c.json
- Update spec boilerplate (copyright, SOTD) to note Media WG ownership
- Update self-references from `wicg.github.io` to `w3c.github.io`
- Add `w3c.json`, contributing and license files
Note the PR depends on https://github.com/tabatkins/bikeshed/pull/1498
... and should only be merged once the repo has been transferred to the W3C organization (#220)
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/mediasession/pull/222.html" title="Last updated on Jul 24, 2019, 2:35 PM UTC (772bbbf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/mediasession/222/7af65e5...tidoust:772bbbf.html" title="Last updated on Jul 24, 2019, 2:35 PM UTC (772bbbf)">Diff</a>
=> Update spec info to point to Media WG

index.bs
The MediaPositionState dictionary cannot take any required
parameters if it is optional when passed to setPositionState().
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/223.html" title="Last updated on Aug 9, 2019, 8:18 PM UTC (302d72b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/223/306f5a3...302d72b.html" title="Last updated on Aug 9, 2019, 8:18 PM UTC (302d72b)">Diff</a>
=> Update MediaPositionState IDL

index.bs
The constructor syntax of `MediaMetadata` interface should be updated to use the new constructor syntax (heycam/webidl#700). This solves https://github.com/w3c/mediasession/issues/235.
***
<a href="https://pr-preview.s3.amazonaws.com/ChunMinChang/mediasession/pull/236.html" title="Last updated on Sep 19, 2019, 4:05 PM UTC (9e92f43)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/236/acd69f9...ChunMinChang:9e92f43.html" title="Last updated on Sep 19, 2019, 4:05 PM UTC (9e92f43)">Diff</a>
=> Use new constructor() syntax

index.bs
The boolean type is `boolean`, not `bool`, in Web IDL:
https://heycam.github.io/webidl/#idl-boolean
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/mediasession/pull/240.html" title="Last updated on Sep 27, 2019, 5:24 PM UTC (0266570)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/240/998ff76...tidoust:0266570.html" title="Last updated on Sep 27, 2019, 5:24 PM UTC (0266570)">Diff</a>
=> Fix fastSeek Web IDL type declaration

index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/242.html" title="Last updated on Oct 9, 2019, 12:44 AM UTC (82e07ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/242/e675c56...82e07ef.html" title="Last updated on Oct 9, 2019, 12:44 AM UTC (82e07ef)">Diff</a>
=> Make setPositionState() parameter syntax valid per WebIDL, fixes #231

index.bs
This PR fixes a minor issue in the Example 3 code.
***
<a href="https://pr-preview.s3.amazonaws.com/chrisn/mediasession/pull/245.html" title="Last updated on Dec 16, 2019, 11:41 AM UTC (424357d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/245/8f181c7...chrisn:424357d.html" title="Last updated on Dec 16, 2019, 11:41 AM UTC (424357d)">Diff</a>
=> Fix code example

index.bs
A few editorial updates to fix a few broken links and references:
- Drop custom dfns that are no longer needed (fixes a few outdated fragments and allows to see which additional dfns the spec needs on top of those that the referenced specs export)
- Replace "triggered by user activation" with new user activation model (see https://github.com/whatwg/html/issues/5129). This may warrant another iteration as I'm not clear whether we're supposed to call the "activation notification" steps
- Update definition of methods to fix IDL links
- Update reference to Web App Manifest and flag the paragraph as informative
- Fix links to "action"
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/mediasession/pull/247.html" title="Last updated on Jan 14, 2020, 6:25 PM UTC (20cef22)">Preview</a> | <a …
=> Fix cross-spec links and references

index.bs
This PR adds the new video conferencing actions as discussed in [issue 264](https://github.com/w3c/mediasession/issues/264)
***
<a href="https://pr-preview.s3.amazonaws.com/steimelchrome/mediasession/pull/269.html" title="Last updated on Apr 28, 2021, 6:49 PM UTC (2de7ecf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/269/5b5ecb5...steimelchrome:2de7ecf.html" title="Last updated on Apr 28, 2021, 6:49 PM UTC (2de7ecf)">Diff</a>
=> Add video conferencing actions to the spec

index.bs
The spec referenced a script on the WHATWG site which (no longer?) exists:
https://resources.whatwg.org/dfn.js
That script should be unnecessary in practice. It prevents the spec from being published to /TR, because external scripts are forbidden.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/270.html" title="Last updated on May 4, 2021, 3:09 PM UTC (702a8c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/270/98a8374...702a8c3.html" title="Last updated on May 4, 2021, 3:09 PM UTC (702a8c3)">Diff</a>
=> Drop non existing external script

index.bs
They are optional and might therefore be unset even if not nullable. No
prose describes when they would be null so letting them be nullable
appears unnecessary.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/226.html" title="Last updated on Aug 15, 2019, 3:12 AM UTC (70f0864)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/226/4b2f4eb...70f0864.html" title="Last updated on Aug 15, 2019, 3:12 AM UTC (70f0864)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/226.html" title="Last updated on Sep 13, 2022, 7:59 AM UTC (a1e8c10)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/226/553bfab...a1e8c10.html" title="Last updated on Sep 13, 2022, 7:59 AM UTC (a1e8c10)">Diff</a>
=> Make MediaSessionActionDetails members non-nullable

index.bs
This PR adds new presenting slides actions as discussed in https://github.com/w3c/mediasession/issues/274#issuecomment-1217121600
It does not add processing rules that allow them to be invoked from Capture Handle Actions yet.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/284.html" title="Last updated on Aug 17, 2022, 6:34 AM UTC (a8d6a5a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/284/84b41c1...a8d6a5a.html" title="Last updated on Aug 17, 2022, 6:34 AM UTC (a8d6a5a)">Diff</a>
=> Add presenting slides actions

index.bs
The `ImageResource` interface graduated to its own spec, and is no longer defined in AppManifest.
The notion of case-sensitivity is also no longer defined in HTML. The Infra spec defines string comparison more precisely through the "is" (or "is identical to") concept.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/mediasession/pull/260.html" title="Last updated on Dec 10, 2020, 10:46 AM UTC (014aac5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/260/5b5ecb5...tidoust:014aac5.html" title="Last updated on Dec 10, 2020, 10:46 AM UTC (014aac5)">Diff</a>
=> Fix refs to ImageResource and string comparison

index.bs
We call it the media session source target.
Make use of it when handling an action, and default to the active media session if the source does not have a target.
Fixes https://github.com/w3c/mediasession/issues/285
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/287.html" title="Last updated on Sep 19, 2022, 9:21 PM UTC (d3f67a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/287/84b41c1...youennf:d3f67a6.html" title="Last updated on Sep 19, 2022, 9:21 PM UTC (d3f67a6)">Diff</a>
=> Introduce the possibility for a source to be tied to a specific media session

index.bs
Remove redundant title attribute.
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/289.html" title="Last updated on Sep 19, 2022, 9:32 PM UTC (aee498f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/289/84b41c1...youennf:aee498f.html" title="Last updated on Sep 19, 2022, 9:32 PM UTC (aee498f)">Diff</a>
=> Remove redundant title attribute

README.md, index.bs
This drops "Standard" from the spec name - @steimelchrome, @youennf are you OK with this change?
See https://github.com/w3c/mediasession/issues/248.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/298.html" title="Last updated on Aug 10, 2023, 4:47 PM UTC (23e1539)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/298/b2914fe...23e1539.html" title="Last updated on Aug 10, 2023, 4:47 PM UTC (23e1539)">Diff</a>
=> Change specification name

index.bs
Set default value to '*' for now until we get a better sense of whether 'self' could be used instead.
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/299.html" title="Last updated on Sep 12, 2023, 9:04 AM UTC (75c372c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/299/79be7cb...youennf:75c372c.html" title="Last updated on Sep 12, 2023, 9:04 AM UTC (75c372c)">Diff</a>
=> Add permissions policy for mediasession

index.bs
Fixes https://github.com/w3c/mediasession/issues/257
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/300.html" title="Last updated on Sep 12, 2023, 4:21 PM UTC (6536edc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/300/79be7cb...youennf:6536edc.html" title="Last updated on Sep 12, 2023, 4:21 PM UTC (6536edc)">Diff</a>
=> Clarify that seekOffset, if present, should be positive.

index.bs
This PR adds a new 'enterpictureinpicture' MediaSessionAction as proposed in issue #294.
Notably, this has an 'automatic' boolean in the given MediaSessionActionDetails. This would allow websites to distinguish between 'enterpictureinpicture' actions coming from an explicit user action (e.g. clicking a picture-in-picture button in the user agent UI) vs the user agent automatically sending the action (e.g. because the website became hidden). This would not require a user agent to *ever* send such an action.
I'm interested in feedback on this approach, and here are two other approaches I considered for allowing a website to distinguish between the two:
1) Having two separate actions for each type ('enterpictureinpicture' and 'enterautopictureinpicture'/'autoenterpictureinpicture')
2) Adding …
=> Add enterpictureinpicture action

index.bs
Fixes #303 
Fixes #252
We make duration a required member of MediaPositionState and add default values for position and playbackRate. duration is now unrestricted to allow Infinity, we add a special check for NaN.
We update MediaSession.setPositionState to accept null since MediaPositionState now has a required member.
This overtakes https://github.com/w3c/mediasession/issues/303 and should fix https://github.com/w3c/mediasession/issues/303 and https://github.com/w3c/mediasession/issues/252.
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/304.html" title="Last updated on Jan 18, 2024, 9:22 AM UTC (5837bd7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/304/5d4054a...youennf:5837bd7.html" title="Last updated on Jan 18, 2024, 9:22 AM …
=> Update MediaPositionState WebIDL

index.bs
Define steps for each of these methods.
Mention the possibility to mute/unmute tracks based on setMicrophoneActive/setCameraActive calls. Mention the possibility for the user agent to deny the mutation of capture states via setMicrophoneActive/setCameraActive calls.
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/312.html" title="Last updated on Feb 14, 2024, 8:23 AM UTC (3cf4e75)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/312/061778a...youennf:3cf4e75.html" title="Last updated on Feb 14, 2024, 8:23 AM UTC (3cf4e75)">Diff</a>
=> Make setMicrophoneActive and setCameraActive return promises.

explainer.md, index.bs
Added a `ChapterInformation` attribute in the `MediaMetadata` to carry the Youtube video chapter data:1) title of the section 2)timestamp of this section 3)screenshot image data of this section
***
<a href="https://pr-preview.s3.amazonaws.com/jiajiabingcheng/mediasession/pull/308.html" title="Last updated on Mar 7, 2024, 1:14 AM UTC (dbf1354)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/308/5d4054a...jiajiabingcheng:dbf1354.html" title="Last updated on Mar 7, 2024, 1:14 AM UTC (dbf1354)">Diff</a>
=> Update index.bs with ChapterInformation

format.py, index.bs
Remove some unnecessary hard links, removes some redundant text ... other little fixes. 
* conformance section is added automatically by bikeshed. No need for an explicit one.
* The old "conforming IDL fragments" text is no longer needed since many years ago.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/310.html" title="Last updated on Apr 14, 2024, 11:15 PM UTC (bf52e90)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/310/c7a47fb...bf52e90.html" title="Last updated on Apr 14, 2024, 11:15 PM UTC (bf52e90)">Diff</a>
=> chore: cleanup bikeshed usage

index.bs
The spec re-defined the `<link>` element with an incorrect fragment. This update uses Bikeshed's "link defaults" mechanism instead to fix the broken link. This would close #324.
The spec also re-defined a couple of terms that did not need to be re-defined (since the HTML spec already exports them). Links to Media Capture and Streams also needed fixing. These issues were reported by Bikeshed during build as warnings.
One problem remains: the reference to "nested browsing contexts" is invalid, see #325.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/326.html" title="Last updated on Apr 17, 2024, 12:39 PM UTC (2eb6f3f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/326/52acdd4...2eb6f3f.html" title="Last updated on Apr 17, 2024, 12:39 PM …
=> Fix references to `<link>`, and a few other concepts

index.bs
Fix https://github.com/w3c/mediasession/issues/339.
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/341.html" title="Last updated on Sep 26, 2024, 5:29 PM UTC (ee415cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/341/0f6e693...youennf:ee415cf.html" title="Last updated on Sep 26, 2024, 5:29 PM UTC (ee415cf)">Diff</a>
=> Queue a task before resolving the promise.

index.bs
Fixes https://github.com/w3c/mediasession/issues/237
Introduce a slot where we store the FrozenArray so that the getter always returns the same object.
Make sure the slot is reset when the setter is called.
Implement the conversion on setter and on getter.
Based on https://github.com/w3c/mediasession/pull/243 work from @ChunMinChang
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/343.html" title="Last updated on Sep 29, 2024, 7:20 PM UTC (6f5ac63)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/343/0f6e693...youennf:6f5ac63.html" title="Last updated on Sep 29, 2024, 7:20 PM UTC (6f5ac63)">Diff</a>
=> Update type of MediaMetadata's artwork

.github/workflows/auto-publish.yml
Needed to get Python >=3.9 for Bikeshed. Also used this opportunity to bump the version of the checkout action used.
Via https://github.com/w3c/mediasession/pull/350#issuecomment-2544853582
=> Bump version of Ubuntu used in job

index.bs
Fixes https://github.com/w3c/mediasession/issues/342
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/354.html" title="Last updated on Jan 21, 2025, 9:01 AM UTC (a9902eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/354/115bf9e...youennf:a9902eb.html" title="Last updated on Jan 21, 2025, 9:01 AM UTC (a9902eb)">Diff</a>
=> Split privacy and security section in two

index.bs
Fixes https://github.com/w3c/mediasession/issues/339
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/352.html" title="Last updated on Jan 23, 2025, 3:11 PM UTC (f67dfd8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/352/081423d...youennf:f67dfd8.html" title="Last updated on Jan 23, 2025, 3:11 PM UTC (f67dfd8)">Diff</a>
=> Queue a task before rejecting the promise in the update capture state algorithm

index.bs
Fixes https://github.com/w3c/mediasession/issues/346
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/359.html" title="Last updated on Apr 15, 2025, 2:32 PM UTC (9dc2811)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/359/906d80b...youennf:9dc2811.html" title="Last updated on Apr 15, 2025, 2:32 PM UTC (9dc2811)">Diff</a>
=> Make a more explicit call to fetch, including options such as destination and mode
