w3c/mediasession

README.md

Extensibility is not a use case, so make separate sections.

Make the "grant access when playback begins" model explicit

---

README.md

This incorporates the use cases from @richtr's repo:
https://github.com/richtr/html-media-focus/blob/gh-pages/USECASES.md

Expand on the use cases with very specific scenarios

---

README.md

The current text seems to imply that volume keys would be handled by the API.

Remove volume as a supported key (closes#10)

---

MediaRemoteControl.md

Adding this for historical reasons and as an input to the discussion.

Mozilla's API proposal (closes #5)

---

mediasession.bs
mediasession.html

Because HTML:
https://html.spec.whatwg.org/#media-data
https://html.spec.whatwg.org/#media-resource

Don't capitalize definitions of media session and media category

---

mediasession.bs
mediasession.html

Relates to https://github.com/whatwg/mediasession/issues/77.

Remove the 'kind' attribute from the MediaSession interface

---

mediasession.bs
mediasession.html

Some internal definintions/algorithms are also renamed.
https://github.com/whatwg/mediasession/issues/47

Rename MediaSession.release() to deactivate()

---

mediasession.bs
mediasession.html

It should not be necessary to say anything normative on the issue, as
the rule is simply that garbage collection should not be observable.
If implementors request guidance, something non-normative can be added.
https://github.com/whatwg/mediasession/issues/86

Remove the section on garbage collection

---

mediasession.bs
mediasession.html

Also drop the table id, as it appears to not be used.

Rename "media session category" to just "media session kind"

---

mediasession.bs
mediasession.html

See also https://github.com/whatwg/html/pull/162

Wordsmith the DOM intro boxes for partial interfaces

---

mediasession.bs
mediasession.html

Fixes https://github.com/whatwg/mediasession/issues/106

Disallow setting mediaElement/audioContext.session when in an active state

---

mediasession.bs
mediasession.html

Also:
* Let MediaSession.deactivate() return a promise.
* Drop implicit activation and decativation for AudioContext.
Fixes https://github.com/whatwg/mediasession/issues/50

Add MediaSession.activate()

---

mediasession.bs
mediasession.html

Context:
https://github.com/whatwg/html/pull/509
https://github.com/heycam/webidl/pull/85
Fixes https://github.com/whatwg/mediasession/issues/121

Use NotAllowedError for activate() promise rejection

---

README.md

Fixes https://github.com/whatwg/mediasession/issues/124

Mention code of conduct in README

---

README.md
use_cases.md

* Adding a link to explainer.md in README.md
* Moving "Use Cases" out to a separate .md file and adding a link in README.md

Cleaning up README.md

---

index.bs

A rough draft for bring back media controls.
A preview of this patch is at:
http://xxyzzzq.github.io/mediasession/

update media controls in spec

---

index.bs

* Removed audio focus from the abstract.
* Keyword fixes for "MAY", "SHOULD", etc.

Fix several wording issues in the spec

---

explainer.md
index.bs

To make it in natural order, s.t. consistent with the order of previous/next track

Reorder seekbackward/forward

---

Makefile

It allows to work on the spec offline and that's amazing :)

Use local bikeshed if installed on the system.

---

index.bs

Add more explanation about selecting tab-level active media session

---

explainer.md

Update explainer.md to match latest version of the specification.

---

index.bs

It's not ideal. It's a bit of monkey patching but better than nothing.

Media session action handler is triggered by user activation (closes #167)

---

index.bs
security-privacy-questionnaire.md

Add Security and Privacy Considerations section and questionnaire (closes #166)

---

index.bs

Various changes

---

index.bs

Add Exposed=Window to MediaMetadata

---

index.bs

Remove auto-pause after the pause action handler and add mention of events for default handlers (fixes #178).

---

explainer.md
index.bs

clearify playbackState and added examples (closes #175, closes #177)

---

index.bs

Fix nit in playbackState example

---

index.bs

List Zhiqiang Zhang as Former Editor.

---

index.bs

I just read through the spec as an initial review and spotted a few improvements that could be made to the spec text. Hope this is OK.

Minor copy edits

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/rebeccahughes/mediasession/pull/209.html" title="Last updated on Mar 7, 2019, 4:37 PM UTC (da0adfa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/mediasession/209/a4d0911...rebeccahughes:da0adfa.html" title="Last updated on Mar 7, 2019, 4:37 PM UTC (da0adfa)">Diff</a>

Add stop action to spec

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/beccahughes/mediasession/pull/211.html" title="Last updated on Jun 20, 2019, 9:31 PM UTC (facb1cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/mediasession/211/6571c4a...beccahughes:facb1cd.html" title="Last updated on Jun 20, 2019, 9:31 PM UTC (facb1cd)">Diff</a>

Add seekto action and MediaSessionActionDetails with action arguments

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/225.html" title="Last updated on Aug 15, 2019, 12:21 AM UTC (c7815a0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/225/4b2f4eb...c7815a0.html" title="Last updated on Aug 15, 2019, 12:21 AM UTC (c7815a0)">Diff</a>

Add Becca Hughes as editor (also add w3cid).

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/249.html" title="Last updated on Feb 3, 2020, 8:14 PM UTC (53630e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/249/c701fea...53630e1.html" title="Last updated on Feb 3, 2020, 8:14 PM UTC (53630e1)">Diff</a>

Link to /TR

---

index.bs

@mounirlamouri
***
<a href="https://pr-preview.s3.amazonaws.com/jpmedley/mediasession/pull/251.html" title="Last updated on Mar 6, 2020, 9:04 PM UTC (fdd4ad8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/251/d794d02...jpmedley:fdd4ad8.html" title="Last updated on Mar 6, 2020, 9:04 PM UTC (fdd4ad8)">Diff</a>

Fix grammar of action definitions.

---

index.bs

Closes #234
***
<a href="https://pr-preview.s3.amazonaws.com/beccahughes/mediasession/pull/253.html" title="Last updated on Mar 18, 2020, 9:32 PM UTC (d86b04b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/253/f0d7199...beccahughes:d86b04b.html" title="Last updated on Mar 18, 2020, 9:32 PM UTC (d86b04b)">Diff</a>

Update media session action details for dictionary changes

---

index.bs

Also move Becca and Mounir to former editors
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/286.html" title="Last updated on Sep 12, 2022, 8:47 PM UTC (71a88e7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/286/84b41c1...youennf:71a88e7.html" title="Last updated on Sep 12, 2022, 8:47 PM UTC (71a88e7)">Diff</a>

Add Tommy and Youenn as editors

---

index.bs

More cleanup of Bikeshed usage... plus little grammar fixes.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/311.html" title="Last updated on Jan 9, 2024, 3:14 AM UTC (99781c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/311/5d4054a...99781c8.html" title="Last updated on Jan 9, 2024, 3:14 AM UTC (99781c8)">Diff</a>

Editorial: more cleanup of BS usage + nits

---

index.bs

Fixes https://github.com/w3c/mediasession/issues/318
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/320.html" title="Last updated on Feb 16, 2024, 8:49 AM UTC (0c51d1d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/320/99e66fc...youennf:0c51d1d.html" title="Last updated on Feb 16, 2024, 8:49 AM UTC (0c51d1d)">Diff</a>

Add MediaSessionActionDetails.isActivating

---

.github/workflows/tidy.yaml

Run the make script to tidy the document after folks commit a PR... in case they forgot to run it.

chore: create tidy.yaml workflow

---

index.bs

Closes #325
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/pull/329.html" title="Last updated on May 13, 2024, 9:56 AM UTC (8b88542)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/329/96d6c04...8b88542.html" title="Last updated on May 13, 2024, 9:56 AM UTC (8b88542)">Diff</a>

Editorial: switch to navigables

---

index.bs

Fixes https://github.com/w3c/mediasession/issues/306
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/319.html" title="Last updated on May 27, 2024, 12:33 PM UTC (6462de8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/319/6879d52...youennf:6462de8.html" title="Last updated on May 27, 2024, 12:33 PM UTC (6462de8)">Diff</a>

Add screenshare support

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/345.html" title="Last updated on Sep 30, 2024, 11:51 PM UTC (0057f8b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/345/51e3cd5...youennf:0057f8b.html" title="Last updated on Sep 30, 2024, 11:51 PM UTC (0057f8b)">Diff</a>

Cleanup spec formatting

---

Makefile
index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediasession/pull/353.html" title="Last updated on Jan 21, 2025, 8:53 AM UTC (e9eaaca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediasession/353/115bf9e...youennf:e9eaaca.html" title="Last updated on Jan 21, 2025, 8:53 AM UTC (e9eaaca)">Diff</a>

Fix bikeshed warnings
